### ISSUE TITLE
File mode in vocabulary scripts

### ISSUE THREAD

**Issue by seanredmond** [NYPL/nypl-core#76]
@nonword @danamansana When running serialize-locations.py I get this error

    serialize-locations.py", line 84, in <module>
        z.write(g.serialize(format="json-ld", context=context))
    TypeError: a bytes-like object is required, not 'str'

This is because the file (`z`) is opened in binary mode

    z = open('../json-ld/locations.json', 'wb')

When it just needs to be `'w'`. I'm running python 3.9.6 which I think is stricter about this than python used to be. It's probably true in all the scripts and needs to be updated everywhere (I'm volunteering to take care of that if you agree)

**Comment by nonword** [comment]
Doing so seems to break things for `3.7.9`. I think opening in binary mode may be valid, but we need to ensure `Graph.serialize` returns the same thing in all `3.7+` python versions. Looks like Graph.serialize` returns bytes by default in python `3.7.9`, but a string in `3.9` - unless `encoding=` is given. Could you take a look at https://github.com/NYPL/nypl-core/pull/77 and see if that change works for your python version?

**Comment by seanredmond** [comment]
#77 runs without the error. What's the motivation to preserve 3.7 compatability?
